#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WebThoiTrang")]
public partial class WebThoiTrangDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertSanPham_Hinh(SanPham_Hinh instance);
  partial void UpdateSanPham_Hinh(SanPham_Hinh instance);
  partial void DeleteSanPham_Hinh(SanPham_Hinh instance);
  partial void InsertTroGiupKH(TroGiupKH instance);
  partial void UpdateTroGiupKH(TroGiupKH instance);
  partial void DeleteTroGiupKH(TroGiupKH instance);
  partial void InsertDonHang(DonHang instance);
  partial void UpdateDonHang(DonHang instance);
  partial void DeleteDonHang(DonHang instance);
  partial void InsertChungLoai(ChungLoai instance);
  partial void UpdateChungLoai(ChungLoai instance);
  partial void DeleteChungLoai(ChungLoai instance);
  partial void InsertLoaiSP(LoaiSP instance);
  partial void UpdateLoaiSP(LoaiSP instance);
  partial void DeleteLoaiSP(LoaiSP instance);
  partial void InsertQuyenTruyCap(QuyenTruyCap instance);
  partial void UpdateQuyenTruyCap(QuyenTruyCap instance);
  partial void DeleteQuyenTruyCap(QuyenTruyCap instance);
  partial void InsertNguoiDung(NguoiDung instance);
  partial void UpdateNguoiDung(NguoiDung instance);
  partial void DeleteNguoiDung(NguoiDung instance);
  partial void InsertLienHe(LienHe instance);
  partial void UpdateLienHe(LienHe instance);
  partial void DeleteLienHe(LienHe instance);
  partial void InsertChiTietDonHang(ChiTietDonHang instance);
  partial void UpdateChiTietDonHang(ChiTietDonHang instance);
  partial void DeleteChiTietDonHang(ChiTietDonHang instance);
  partial void InsertSanPham(SanPham instance);
  partial void UpdateSanPham(SanPham instance);
  partial void DeleteSanPham(SanPham instance);
  #endregion
	
	public WebThoiTrangDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["WebThoiTrangConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public WebThoiTrangDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public WebThoiTrangDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public WebThoiTrangDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public WebThoiTrangDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<SanPham_Hinh> SanPham_Hinhs
	{
		get
		{
			return this.GetTable<SanPham_Hinh>();
		}
	}
	
	public System.Data.Linq.Table<TroGiupKH> TroGiupKHs
	{
		get
		{
			return this.GetTable<TroGiupKH>();
		}
	}
	
	public System.Data.Linq.Table<DonHang> DonHangs
	{
		get
		{
			return this.GetTable<DonHang>();
		}
	}
	
	public System.Data.Linq.Table<ChungLoai> ChungLoais
	{
		get
		{
			return this.GetTable<ChungLoai>();
		}
	}
	
	public System.Data.Linq.Table<LoaiSP> LoaiSPs
	{
		get
		{
			return this.GetTable<LoaiSP>();
		}
	}
	
	public System.Data.Linq.Table<QuyenTruyCap> QuyenTruyCaps
	{
		get
		{
			return this.GetTable<QuyenTruyCap>();
		}
	}
	
	public System.Data.Linq.Table<NguoiDung> NguoiDungs
	{
		get
		{
			return this.GetTable<NguoiDung>();
		}
	}
	
	public System.Data.Linq.Table<LienHe> LienHes
	{
		get
		{
			return this.GetTable<LienHe>();
		}
	}
	
	public System.Data.Linq.Table<ChiTietDonHang> ChiTietDonHangs
	{
		get
		{
			return this.GetTable<ChiTietDonHang>();
		}
	}
	
	public System.Data.Linq.Table<SanPham> SanPhams
	{
		get
		{
			return this.GetTable<SanPham>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SanPham_Hinh")]
public partial class SanPham_Hinh : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idHinh;
	
	private System.Nullable<int> _idSP;
	
	private string _UrlHinh;
	
	private System.Nullable<int> _Stt;
	
	private System.Nullable<int> _AnHien;
	
	private EntityRef<SanPham> _SanPham;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidHinhChanging(int value);
    partial void OnidHinhChanged();
    partial void OnidSPChanging(System.Nullable<int> value);
    partial void OnidSPChanged();
    partial void OnUrlHinhChanging(string value);
    partial void OnUrlHinhChanged();
    partial void OnSttChanging(System.Nullable<int> value);
    partial void OnSttChanged();
    partial void OnAnHienChanging(System.Nullable<int> value);
    partial void OnAnHienChanged();
    #endregion
	
	public SanPham_Hinh()
	{
		this._SanPham = default(EntityRef<SanPham>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idHinh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int idHinh
	{
		get
		{
			return this._idHinh;
		}
		set
		{
			if ((this._idHinh != value))
			{
				this.OnidHinhChanging(value);
				this.SendPropertyChanging();
				this._idHinh = value;
				this.SendPropertyChanged("idHinh");
				this.OnidHinhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSP", DbType="Int")]
	public System.Nullable<int> idSP
	{
		get
		{
			return this._idSP;
		}
		set
		{
			if ((this._idSP != value))
			{
				if (this._SanPham.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnidSPChanging(value);
				this.SendPropertyChanging();
				this._idSP = value;
				this.SendPropertyChanged("idSP");
				this.OnidSPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrlHinh", DbType="NVarChar(500)")]
	public string UrlHinh
	{
		get
		{
			return this._UrlHinh;
		}
		set
		{
			if ((this._UrlHinh != value))
			{
				this.OnUrlHinhChanging(value);
				this.SendPropertyChanging();
				this._UrlHinh = value;
				this.SendPropertyChanged("UrlHinh");
				this.OnUrlHinhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stt", DbType="Int")]
	public System.Nullable<int> Stt
	{
		get
		{
			return this._Stt;
		}
		set
		{
			if ((this._Stt != value))
			{
				this.OnSttChanging(value);
				this.SendPropertyChanging();
				this._Stt = value;
				this.SendPropertyChanged("Stt");
				this.OnSttChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnHien", DbType="Int")]
	public System.Nullable<int> AnHien
	{
		get
		{
			return this._AnHien;
		}
		set
		{
			if ((this._AnHien != value))
			{
				this.OnAnHienChanging(value);
				this.SendPropertyChanging();
				this._AnHien = value;
				this.SendPropertyChanged("AnHien");
				this.OnAnHienChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_SanPham_Hinh", Storage="_SanPham", ThisKey="idSP", OtherKey="idSP", IsForeignKey=true)]
	public SanPham SanPham
	{
		get
		{
			return this._SanPham.Entity;
		}
		set
		{
			SanPham previousValue = this._SanPham.Entity;
			if (((previousValue != value) 
						|| (this._SanPham.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._SanPham.Entity = null;
					previousValue.SanPham_Hinhs.Remove(this);
				}
				this._SanPham.Entity = value;
				if ((value != null))
				{
					value.SanPham_Hinhs.Add(this);
					this._idSP = value.idSP;
				}
				else
				{
					this._idSP = default(Nullable<int>);
				}
				this.SendPropertyChanged("SanPham");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TroGiupKH")]
public partial class TroGiupKH : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idLL;
	
	private string _LoiKhuyen;
	
	private string _DienThoai;
	
	private string _Email;
	
	private string _DiaChi;
	
	private string _TGLamViec;
	
	private string _ChiNhanhCoHang;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidLLChanging(int value);
    partial void OnidLLChanged();
    partial void OnLoiKhuyenChanging(string value);
    partial void OnLoiKhuyenChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnTGLamViecChanging(string value);
    partial void OnTGLamViecChanged();
    partial void OnChiNhanhCoHangChanging(string value);
    partial void OnChiNhanhCoHangChanged();
    #endregion
	
	public TroGiupKH()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idLL", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int idLL
	{
		get
		{
			return this._idLL;
		}
		set
		{
			if ((this._idLL != value))
			{
				this.OnidLLChanging(value);
				this.SendPropertyChanging();
				this._idLL = value;
				this.SendPropertyChanged("idLL");
				this.OnidLLChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoiKhuyen", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string LoiKhuyen
	{
		get
		{
			return this._LoiKhuyen;
		}
		set
		{
			if ((this._LoiKhuyen != value))
			{
				this.OnLoiKhuyenChanging(value);
				this.SendPropertyChanging();
				this._LoiKhuyen = value;
				this.SendPropertyChanged("LoiKhuyen");
				this.OnLoiKhuyenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(100)")]
	public string DienThoai
	{
		get
		{
			return this._DienThoai;
		}
		set
		{
			if ((this._DienThoai != value))
			{
				this.OnDienThoaiChanging(value);
				this.SendPropertyChanging();
				this._DienThoai = value;
				this.SendPropertyChanged("DienThoai");
				this.OnDienThoaiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string DiaChi
	{
		get
		{
			return this._DiaChi;
		}
		set
		{
			if ((this._DiaChi != value))
			{
				this.OnDiaChiChanging(value);
				this.SendPropertyChanging();
				this._DiaChi = value;
				this.SendPropertyChanged("DiaChi");
				this.OnDiaChiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGLamViec", DbType="NVarChar(100)")]
	public string TGLamViec
	{
		get
		{
			return this._TGLamViec;
		}
		set
		{
			if ((this._TGLamViec != value))
			{
				this.OnTGLamViecChanging(value);
				this.SendPropertyChanging();
				this._TGLamViec = value;
				this.SendPropertyChanged("TGLamViec");
				this.OnTGLamViecChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiNhanhCoHang", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string ChiNhanhCoHang
	{
		get
		{
			return this._ChiNhanhCoHang;
		}
		set
		{
			if ((this._ChiNhanhCoHang != value))
			{
				this.OnChiNhanhCoHangChanging(value);
				this.SendPropertyChanging();
				this._ChiNhanhCoHang = value;
				this.SendPropertyChanged("ChiNhanhCoHang");
				this.OnChiNhanhCoHangChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonHang")]
public partial class DonHang : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idDHang;
	
	private System.Nullable<System.DateTime> _ThoiDiemDatHang;
	
	private string _TenNguoiNhan;
	
	private string _SoDT;
	
	private string _Email;
	
	private string _DiaChiGiaoHang;
	
	private System.Nullable<int> _TinhTrang;
	
	private string _GhiChu;
	
	private EntitySet<ChiTietDonHang> _ChiTietDonHangs;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDHangChanging(int value);
    partial void OnidDHangChanged();
    partial void OnThoiDiemDatHangChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiDiemDatHangChanged();
    partial void OnTenNguoiNhanChanging(string value);
    partial void OnTenNguoiNhanChanged();
    partial void OnSoDTChanging(string value);
    partial void OnSoDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDiaChiGiaoHangChanging(string value);
    partial void OnDiaChiGiaoHangChanged();
    partial void OnTinhTrangChanging(System.Nullable<int> value);
    partial void OnTinhTrangChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
	
	public DonHang()
	{
		this._ChiTietDonHangs = new EntitySet<ChiTietDonHang>(new Action<ChiTietDonHang>(this.attach_ChiTietDonHangs), new Action<ChiTietDonHang>(this.detach_ChiTietDonHangs));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDHang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int idDHang
	{
		get
		{
			return this._idDHang;
		}
		set
		{
			if ((this._idDHang != value))
			{
				this.OnidDHangChanging(value);
				this.SendPropertyChanging();
				this._idDHang = value;
				this.SendPropertyChanged("idDHang");
				this.OnidDHangChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiDiemDatHang", DbType="DateTime")]
	public System.Nullable<System.DateTime> ThoiDiemDatHang
	{
		get
		{
			return this._ThoiDiemDatHang;
		}
		set
		{
			if ((this._ThoiDiemDatHang != value))
			{
				this.OnThoiDiemDatHangChanging(value);
				this.SendPropertyChanging();
				this._ThoiDiemDatHang = value;
				this.SendPropertyChanged("ThoiDiemDatHang");
				this.OnThoiDiemDatHangChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiNhan", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
	public string TenNguoiNhan
	{
		get
		{
			return this._TenNguoiNhan;
		}
		set
		{
			if ((this._TenNguoiNhan != value))
			{
				this.OnTenNguoiNhanChanging(value);
				this.SendPropertyChanging();
				this._TenNguoiNhan = value;
				this.SendPropertyChanged("TenNguoiNhan");
				this.OnTenNguoiNhanChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDT", DbType="VarChar(20)")]
	public string SoDT
	{
		get
		{
			return this._SoDT;
		}
		set
		{
			if ((this._SoDT != value))
			{
				this.OnSoDTChanging(value);
				this.SendPropertyChanging();
				this._SoDT = value;
				this.SendPropertyChanged("SoDT");
				this.OnSoDTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiGiaoHang", DbType="NVarChar(500)")]
	public string DiaChiGiaoHang
	{
		get
		{
			return this._DiaChiGiaoHang;
		}
		set
		{
			if ((this._DiaChiGiaoHang != value))
			{
				this.OnDiaChiGiaoHangChanging(value);
				this.SendPropertyChanging();
				this._DiaChiGiaoHang = value;
				this.SendPropertyChanged("DiaChiGiaoHang");
				this.OnDiaChiGiaoHangChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Int")]
	public System.Nullable<int> TinhTrang
	{
		get
		{
			return this._TinhTrang;
		}
		set
		{
			if ((this._TinhTrang != value))
			{
				this.OnTinhTrangChanging(value);
				this.SendPropertyChanging();
				this._TinhTrang = value;
				this.SendPropertyChanged("TinhTrang");
				this.OnTinhTrangChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string GhiChu
	{
		get
		{
			return this._GhiChu;
		}
		set
		{
			if ((this._GhiChu != value))
			{
				this.OnGhiChuChanging(value);
				this.SendPropertyChanging();
				this._GhiChu = value;
				this.SendPropertyChanged("GhiChu");
				this.OnGhiChuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonHang_ChiTietDonHang", Storage="_ChiTietDonHangs", ThisKey="idDHang", OtherKey="idDHang")]
	public EntitySet<ChiTietDonHang> ChiTietDonHangs
	{
		get
		{
			return this._ChiTietDonHangs;
		}
		set
		{
			this._ChiTietDonHangs.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_ChiTietDonHangs(ChiTietDonHang entity)
	{
		this.SendPropertyChanging();
		entity.DonHang = this;
	}
	
	private void detach_ChiTietDonHangs(ChiTietDonHang entity)
	{
		this.SendPropertyChanging();
		entity.DonHang = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChungLoai")]
public partial class ChungLoai : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idCL;
	
	private string _TenCL;
	
	private System.Nullable<int> _AnHien;
	
	private EntitySet<LoaiSP> _LoaiSPs;
	
	private EntitySet<SanPham> _SanPhams;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCLChanging(int value);
    partial void OnidCLChanged();
    partial void OnTenCLChanging(string value);
    partial void OnTenCLChanged();
    partial void OnAnHienChanging(System.Nullable<int> value);
    partial void OnAnHienChanged();
    #endregion
	
	public ChungLoai()
	{
		this._LoaiSPs = new EntitySet<LoaiSP>(new Action<LoaiSP>(this.attach_LoaiSPs), new Action<LoaiSP>(this.detach_LoaiSPs));
		this._SanPhams = new EntitySet<SanPham>(new Action<SanPham>(this.attach_SanPhams), new Action<SanPham>(this.detach_SanPhams));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCL", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int idCL
	{
		get
		{
			return this._idCL;
		}
		set
		{
			if ((this._idCL != value))
			{
				this.OnidCLChanging(value);
				this.SendPropertyChanging();
				this._idCL = value;
				this.SendPropertyChanged("idCL");
				this.OnidCLChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCL", DbType="NVarChar(500)")]
	public string TenCL
	{
		get
		{
			return this._TenCL;
		}
		set
		{
			if ((this._TenCL != value))
			{
				this.OnTenCLChanging(value);
				this.SendPropertyChanging();
				this._TenCL = value;
				this.SendPropertyChanged("TenCL");
				this.OnTenCLChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnHien", DbType="Int")]
	public System.Nullable<int> AnHien
	{
		get
		{
			return this._AnHien;
		}
		set
		{
			if ((this._AnHien != value))
			{
				this.OnAnHienChanging(value);
				this.SendPropertyChanging();
				this._AnHien = value;
				this.SendPropertyChanged("AnHien");
				this.OnAnHienChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChungLoai_LoaiSP", Storage="_LoaiSPs", ThisKey="idCL", OtherKey="idCL")]
	public EntitySet<LoaiSP> LoaiSPs
	{
		get
		{
			return this._LoaiSPs;
		}
		set
		{
			this._LoaiSPs.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChungLoai_SanPham", Storage="_SanPhams", ThisKey="idCL", OtherKey="idCL")]
	public EntitySet<SanPham> SanPhams
	{
		get
		{
			return this._SanPhams;
		}
		set
		{
			this._SanPhams.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_LoaiSPs(LoaiSP entity)
	{
		this.SendPropertyChanging();
		entity.ChungLoai = this;
	}
	
	private void detach_LoaiSPs(LoaiSP entity)
	{
		this.SendPropertyChanging();
		entity.ChungLoai = null;
	}
	
	private void attach_SanPhams(SanPham entity)
	{
		this.SendPropertyChanging();
		entity.ChungLoai = this;
	}
	
	private void detach_SanPhams(SanPham entity)
	{
		this.SendPropertyChanging();
		entity.ChungLoai = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiSP")]
public partial class LoaiSP : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idLoai;
	
	private System.Nullable<int> _idCL;
	
	private string _TenLoai;
	
	private System.Nullable<int> _AnHien;
	
	private EntitySet<SanPham> _SanPhams;
	
	private EntityRef<ChungLoai> _ChungLoai;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidLoaiChanging(int value);
    partial void OnidLoaiChanged();
    partial void OnidCLChanging(System.Nullable<int> value);
    partial void OnidCLChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    partial void OnAnHienChanging(System.Nullable<int> value);
    partial void OnAnHienChanged();
    #endregion
	
	public LoaiSP()
	{
		this._SanPhams = new EntitySet<SanPham>(new Action<SanPham>(this.attach_SanPhams), new Action<SanPham>(this.detach_SanPhams));
		this._ChungLoai = default(EntityRef<ChungLoai>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idLoai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int idLoai
	{
		get
		{
			return this._idLoai;
		}
		set
		{
			if ((this._idLoai != value))
			{
				this.OnidLoaiChanging(value);
				this.SendPropertyChanging();
				this._idLoai = value;
				this.SendPropertyChanged("idLoai");
				this.OnidLoaiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCL", DbType="Int")]
	public System.Nullable<int> idCL
	{
		get
		{
			return this._idCL;
		}
		set
		{
			if ((this._idCL != value))
			{
				if (this._ChungLoai.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnidCLChanging(value);
				this.SendPropertyChanging();
				this._idCL = value;
				this.SendPropertyChanged("idCL");
				this.OnidCLChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(500)")]
	public string TenLoai
	{
		get
		{
			return this._TenLoai;
		}
		set
		{
			if ((this._TenLoai != value))
			{
				this.OnTenLoaiChanging(value);
				this.SendPropertyChanging();
				this._TenLoai = value;
				this.SendPropertyChanged("TenLoai");
				this.OnTenLoaiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnHien", DbType="Int")]
	public System.Nullable<int> AnHien
	{
		get
		{
			return this._AnHien;
		}
		set
		{
			if ((this._AnHien != value))
			{
				this.OnAnHienChanging(value);
				this.SendPropertyChanging();
				this._AnHien = value;
				this.SendPropertyChanged("AnHien");
				this.OnAnHienChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiSP_SanPham", Storage="_SanPhams", ThisKey="idLoai", OtherKey="idLoai")]
	public EntitySet<SanPham> SanPhams
	{
		get
		{
			return this._SanPhams;
		}
		set
		{
			this._SanPhams.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChungLoai_LoaiSP", Storage="_ChungLoai", ThisKey="idCL", OtherKey="idCL", IsForeignKey=true)]
	public ChungLoai ChungLoai
	{
		get
		{
			return this._ChungLoai.Entity;
		}
		set
		{
			ChungLoai previousValue = this._ChungLoai.Entity;
			if (((previousValue != value) 
						|| (this._ChungLoai.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._ChungLoai.Entity = null;
					previousValue.LoaiSPs.Remove(this);
				}
				this._ChungLoai.Entity = value;
				if ((value != null))
				{
					value.LoaiSPs.Add(this);
					this._idCL = value.idCL;
				}
				else
				{
					this._idCL = default(Nullable<int>);
				}
				this.SendPropertyChanged("ChungLoai");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_SanPhams(SanPham entity)
	{
		this.SendPropertyChanging();
		entity.LoaiSP = this;
	}
	
	private void detach_SanPhams(SanPham entity)
	{
		this.SendPropertyChanging();
		entity.LoaiSP = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuyenTruyCap")]
public partial class QuyenTruyCap : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idQuyen;
	
	private string _TenQuyen;
	
	private EntitySet<NguoiDung> _NguoiDungs;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidQuyenChanging(int value);
    partial void OnidQuyenChanged();
    partial void OnTenQuyenChanging(string value);
    partial void OnTenQuyenChanged();
    #endregion
	
	public QuyenTruyCap()
	{
		this._NguoiDungs = new EntitySet<NguoiDung>(new Action<NguoiDung>(this.attach_NguoiDungs), new Action<NguoiDung>(this.detach_NguoiDungs));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idQuyen", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int idQuyen
	{
		get
		{
			return this._idQuyen;
		}
		set
		{
			if ((this._idQuyen != value))
			{
				this.OnidQuyenChanging(value);
				this.SendPropertyChanging();
				this._idQuyen = value;
				this.SendPropertyChanged("idQuyen");
				this.OnidQuyenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuyen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string TenQuyen
	{
		get
		{
			return this._TenQuyen;
		}
		set
		{
			if ((this._TenQuyen != value))
			{
				this.OnTenQuyenChanging(value);
				this.SendPropertyChanging();
				this._TenQuyen = value;
				this.SendPropertyChanged("TenQuyen");
				this.OnTenQuyenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuyenTruyCap_NguoiDung", Storage="_NguoiDungs", ThisKey="idQuyen", OtherKey="idQuyen")]
	public EntitySet<NguoiDung> NguoiDungs
	{
		get
		{
			return this._NguoiDungs;
		}
		set
		{
			this._NguoiDungs.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_NguoiDungs(NguoiDung entity)
	{
		this.SendPropertyChanging();
		entity.QuyenTruyCap = this;
	}
	
	private void detach_NguoiDungs(NguoiDung entity)
	{
		this.SendPropertyChanging();
		entity.QuyenTruyCap = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idUser;
	
	private string _HoTen;
	
	private string _Username;
	
	private string _Password;
	
	private string _DiaChi;
	
	private string _DienThoai;
	
	private string _Email;
	
	private System.Nullable<System.DateTime> _NgayDangKy;
	
	private System.Nullable<System.DateTime> _NgaySinh;
	
	private int _GioiTinh;
	
	private int _idQuyen;
	
	private EntityRef<QuyenTruyCap> _QuyenTruyCap;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidUserChanging(int value);
    partial void OnidUserChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNgayDangKyChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDangKyChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(int value);
    partial void OnGioiTinhChanged();
    partial void OnidQuyenChanging(int value);
    partial void OnidQuyenChanged();
    #endregion
	
	public NguoiDung()
	{
		this._QuyenTruyCap = default(EntityRef<QuyenTruyCap>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUser", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int idUser
	{
		get
		{
			return this._idUser;
		}
		set
		{
			if ((this._idUser != value))
			{
				this.OnidUserChanging(value);
				this.SendPropertyChanging();
				this._idUser = value;
				this.SendPropertyChanged("idUser");
				this.OnidUserChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
	public string HoTen
	{
		get
		{
			return this._HoTen;
		}
		set
		{
			if ((this._HoTen != value))
			{
				this.OnHoTenChanging(value);
				this.SendPropertyChanging();
				this._HoTen = value;
				this.SendPropertyChanged("HoTen");
				this.OnHoTenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
	public string Username
	{
		get
		{
			return this._Username;
		}
		set
		{
			if ((this._Username != value))
			{
				this.OnUsernameChanging(value);
				this.SendPropertyChanging();
				this._Username = value;
				this.SendPropertyChanged("Username");
				this.OnUsernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
	public string DiaChi
	{
		get
		{
			return this._DiaChi;
		}
		set
		{
			if ((this._DiaChi != value))
			{
				this.OnDiaChiChanging(value);
				this.SendPropertyChanging();
				this._DiaChi = value;
				this.SendPropertyChanged("DiaChi");
				this.OnDiaChiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string DienThoai
	{
		get
		{
			return this._DienThoai;
		}
		set
		{
			if ((this._DienThoai != value))
			{
				this.OnDienThoaiChanging(value);
				this.SendPropertyChanging();
				this._DienThoai = value;
				this.SendPropertyChanged("DienThoai");
				this.OnDienThoaiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDangKy", DbType="DateTime")]
	public System.Nullable<System.DateTime> NgayDangKy
	{
		get
		{
			return this._NgayDangKy;
		}
		set
		{
			if ((this._NgayDangKy != value))
			{
				this.OnNgayDangKyChanging(value);
				this.SendPropertyChanging();
				this._NgayDangKy = value;
				this.SendPropertyChanged("NgayDangKy");
				this.OnNgayDangKyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
	public System.Nullable<System.DateTime> NgaySinh
	{
		get
		{
			return this._NgaySinh;
		}
		set
		{
			if ((this._NgaySinh != value))
			{
				this.OnNgaySinhChanging(value);
				this.SendPropertyChanging();
				this._NgaySinh = value;
				this.SendPropertyChanged("NgaySinh");
				this.OnNgaySinhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Int NOT NULL")]
	public int GioiTinh
	{
		get
		{
			return this._GioiTinh;
		}
		set
		{
			if ((this._GioiTinh != value))
			{
				this.OnGioiTinhChanging(value);
				this.SendPropertyChanging();
				this._GioiTinh = value;
				this.SendPropertyChanged("GioiTinh");
				this.OnGioiTinhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idQuyen", DbType="Int NOT NULL")]
	public int idQuyen
	{
		get
		{
			return this._idQuyen;
		}
		set
		{
			if ((this._idQuyen != value))
			{
				if (this._QuyenTruyCap.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnidQuyenChanging(value);
				this.SendPropertyChanging();
				this._idQuyen = value;
				this.SendPropertyChanged("idQuyen");
				this.OnidQuyenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuyenTruyCap_NguoiDung", Storage="_QuyenTruyCap", ThisKey="idQuyen", OtherKey="idQuyen", IsForeignKey=true)]
	public QuyenTruyCap QuyenTruyCap
	{
		get
		{
			return this._QuyenTruyCap.Entity;
		}
		set
		{
			QuyenTruyCap previousValue = this._QuyenTruyCap.Entity;
			if (((previousValue != value) 
						|| (this._QuyenTruyCap.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._QuyenTruyCap.Entity = null;
					previousValue.NguoiDungs.Remove(this);
				}
				this._QuyenTruyCap.Entity = value;
				if ((value != null))
				{
					value.NguoiDungs.Add(this);
					this._idQuyen = value.idQuyen;
				}
				else
				{
					this._idQuyen = default(int);
				}
				this.SendPropertyChanged("QuyenTruyCap");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LienHe")]
public partial class LienHe : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idLienLac;
	
	private string _HoTen;
	
	private string _Email;
	
	private string _SDT;
	
	private string _DiaChi;
	
	private string _ChuDe;
	
	private string _NoiDung;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidLienLacChanging(int value);
    partial void OnidLienLacChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnChuDeChanging(string value);
    partial void OnChuDeChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    #endregion
	
	public LienHe()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idLienLac", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int idLienLac
	{
		get
		{
			return this._idLienLac;
		}
		set
		{
			if ((this._idLienLac != value))
			{
				this.OnidLienLacChanging(value);
				this.SendPropertyChanging();
				this._idLienLac = value;
				this.SendPropertyChanged("idLienLac");
				this.OnidLienLacChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100)")]
	public string HoTen
	{
		get
		{
			return this._HoTen;
		}
		set
		{
			if ((this._HoTen != value))
			{
				this.OnHoTenChanging(value);
				this.SendPropertyChanging();
				this._HoTen = value;
				this.SendPropertyChanged("HoTen");
				this.OnHoTenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(50)")]
	public string SDT
	{
		get
		{
			return this._SDT;
		}
		set
		{
			if ((this._SDT != value))
			{
				this.OnSDTChanging(value);
				this.SendPropertyChanging();
				this._SDT = value;
				this.SendPropertyChanged("SDT");
				this.OnSDTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(500)")]
	public string DiaChi
	{
		get
		{
			return this._DiaChi;
		}
		set
		{
			if ((this._DiaChi != value))
			{
				this.OnDiaChiChanging(value);
				this.SendPropertyChanging();
				this._DiaChi = value;
				this.SendPropertyChanged("DiaChi");
				this.OnDiaChiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuDe", DbType="NVarChar(100)")]
	public string ChuDe
	{
		get
		{
			return this._ChuDe;
		}
		set
		{
			if ((this._ChuDe != value))
			{
				this.OnChuDeChanging(value);
				this.SendPropertyChanging();
				this._ChuDe = value;
				this.SendPropertyChanged("ChuDe");
				this.OnChuDeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string NoiDung
	{
		get
		{
			return this._NoiDung;
		}
		set
		{
			if ((this._NoiDung != value))
			{
				this.OnNoiDungChanging(value);
				this.SendPropertyChanging();
				this._NoiDung = value;
				this.SendPropertyChanged("NoiDung");
				this.OnNoiDungChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietDonHang")]
public partial class ChiTietDonHang : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idDHang;
	
	private int _idSP;
	
	private string _Size;
	
	private System.Nullable<int> _SoLuong;
	
	private System.Nullable<double> _Gia;
	
	private EntityRef<DonHang> _DonHang;
	
	private EntityRef<SanPham> _SanPham;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDHangChanging(int value);
    partial void OnidDHangChanged();
    partial void OnidSPChanging(int value);
    partial void OnidSPChanged();
    partial void OnSizeChanging(string value);
    partial void OnSizeChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnGiaChanging(System.Nullable<double> value);
    partial void OnGiaChanged();
    #endregion
	
	public ChiTietDonHang()
	{
		this._DonHang = default(EntityRef<DonHang>);
		this._SanPham = default(EntityRef<SanPham>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDHang", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int idDHang
	{
		get
		{
			return this._idDHang;
		}
		set
		{
			if ((this._idDHang != value))
			{
				if (this._DonHang.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnidDHangChanging(value);
				this.SendPropertyChanging();
				this._idDHang = value;
				this.SendPropertyChanged("idDHang");
				this.OnidDHangChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSP", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int idSP
	{
		get
		{
			return this._idSP;
		}
		set
		{
			if ((this._idSP != value))
			{
				if (this._SanPham.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnidSPChanging(value);
				this.SendPropertyChanging();
				this._idSP = value;
				this.SendPropertyChanged("idSP");
				this.OnidSPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="VarChar(10)")]
	public string Size
	{
		get
		{
			return this._Size;
		}
		set
		{
			if ((this._Size != value))
			{
				this.OnSizeChanging(value);
				this.SendPropertyChanging();
				this._Size = value;
				this.SendPropertyChanged("Size");
				this.OnSizeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
	public System.Nullable<int> SoLuong
	{
		get
		{
			return this._SoLuong;
		}
		set
		{
			if ((this._SoLuong != value))
			{
				this.OnSoLuongChanging(value);
				this.SendPropertyChanging();
				this._SoLuong = value;
				this.SendPropertyChanged("SoLuong");
				this.OnSoLuongChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Float")]
	public System.Nullable<double> Gia
	{
		get
		{
			return this._Gia;
		}
		set
		{
			if ((this._Gia != value))
			{
				this.OnGiaChanging(value);
				this.SendPropertyChanging();
				this._Gia = value;
				this.SendPropertyChanged("Gia");
				this.OnGiaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonHang_ChiTietDonHang", Storage="_DonHang", ThisKey="idDHang", OtherKey="idDHang", IsForeignKey=true)]
	public DonHang DonHang
	{
		get
		{
			return this._DonHang.Entity;
		}
		set
		{
			DonHang previousValue = this._DonHang.Entity;
			if (((previousValue != value) 
						|| (this._DonHang.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._DonHang.Entity = null;
					previousValue.ChiTietDonHangs.Remove(this);
				}
				this._DonHang.Entity = value;
				if ((value != null))
				{
					value.ChiTietDonHangs.Add(this);
					this._idDHang = value.idDHang;
				}
				else
				{
					this._idDHang = default(int);
				}
				this.SendPropertyChanged("DonHang");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_ChiTietDonHang", Storage="_SanPham", ThisKey="idSP", OtherKey="idSP", IsForeignKey=true)]
	public SanPham SanPham
	{
		get
		{
			return this._SanPham.Entity;
		}
		set
		{
			SanPham previousValue = this._SanPham.Entity;
			if (((previousValue != value) 
						|| (this._SanPham.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._SanPham.Entity = null;
					previousValue.ChiTietDonHangs.Remove(this);
				}
				this._SanPham.Entity = value;
				if ((value != null))
				{
					value.ChiTietDonHangs.Add(this);
					this._idSP = value.idSP;
				}
				else
				{
					this._idSP = default(int);
				}
				this.SendPropertyChanged("SanPham");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SanPham")]
public partial class SanPham : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idSP;
	
	private System.Nullable<int> _idLoai;
	
	private System.Nullable<int> _idCL;
	
	private string _TenSP;
	
	private string _MoTa;
	
	private System.Nullable<System.DateTime> _NgayCapNhat;
	
	private string _Size;
	
	private System.Nullable<int> _Gia;
	
	private string _UrlHinh;
	
	private System.Nullable<int> _SoLuongTonKho;
	
	private string _GhiChu;
	
	private System.Nullable<int> _AnHien;
	
	private EntitySet<SanPham_Hinh> _SanPham_Hinhs;
	
	private EntitySet<ChiTietDonHang> _ChiTietDonHangs;
	
	private EntityRef<LoaiSP> _LoaiSP;
	
	private EntityRef<ChungLoai> _ChungLoai;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidSPChanging(int value);
    partial void OnidSPChanged();
    partial void OnidLoaiChanging(System.Nullable<int> value);
    partial void OnidLoaiChanged();
    partial void OnidCLChanging(System.Nullable<int> value);
    partial void OnidCLChanged();
    partial void OnTenSPChanging(string value);
    partial void OnTenSPChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnNgayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhatChanged();
    partial void OnSizeChanging(string value);
    partial void OnSizeChanged();
    partial void OnGiaChanging(System.Nullable<int> value);
    partial void OnGiaChanged();
    partial void OnUrlHinhChanging(string value);
    partial void OnUrlHinhChanged();
    partial void OnSoLuongTonKhoChanging(System.Nullable<int> value);
    partial void OnSoLuongTonKhoChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnAnHienChanging(System.Nullable<int> value);
    partial void OnAnHienChanged();
    #endregion
	
	public SanPham()
	{
		this._SanPham_Hinhs = new EntitySet<SanPham_Hinh>(new Action<SanPham_Hinh>(this.attach_SanPham_Hinhs), new Action<SanPham_Hinh>(this.detach_SanPham_Hinhs));
		this._ChiTietDonHangs = new EntitySet<ChiTietDonHang>(new Action<ChiTietDonHang>(this.attach_ChiTietDonHangs), new Action<ChiTietDonHang>(this.detach_ChiTietDonHangs));
		this._LoaiSP = default(EntityRef<LoaiSP>);
		this._ChungLoai = default(EntityRef<ChungLoai>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int idSP
	{
		get
		{
			return this._idSP;
		}
		set
		{
			if ((this._idSP != value))
			{
				this.OnidSPChanging(value);
				this.SendPropertyChanging();
				this._idSP = value;
				this.SendPropertyChanged("idSP");
				this.OnidSPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idLoai", DbType="Int")]
	public System.Nullable<int> idLoai
	{
		get
		{
			return this._idLoai;
		}
		set
		{
			if ((this._idLoai != value))
			{
				if (this._LoaiSP.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnidLoaiChanging(value);
				this.SendPropertyChanging();
				this._idLoai = value;
				this.SendPropertyChanged("idLoai");
				this.OnidLoaiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCL", DbType="Int")]
	public System.Nullable<int> idCL
	{
		get
		{
			return this._idCL;
		}
		set
		{
			if ((this._idCL != value))
			{
				if (this._ChungLoai.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnidCLChanging(value);
				this.SendPropertyChanging();
				this._idCL = value;
				this.SendPropertyChanged("idCL");
				this.OnidCLChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSP", DbType="NVarChar(500)")]
	public string TenSP
	{
		get
		{
			return this._TenSP;
		}
		set
		{
			if ((this._TenSP != value))
			{
				this.OnTenSPChanging(value);
				this.SendPropertyChanging();
				this._TenSP = value;
				this.SendPropertyChanged("TenSP");
				this.OnTenSPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string MoTa
	{
		get
		{
			return this._MoTa;
		}
		set
		{
			if ((this._MoTa != value))
			{
				this.OnMoTaChanging(value);
				this.SendPropertyChanging();
				this._MoTa = value;
				this.SendPropertyChanged("MoTa");
				this.OnMoTaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime")]
	public System.Nullable<System.DateTime> NgayCapNhat
	{
		get
		{
			return this._NgayCapNhat;
		}
		set
		{
			if ((this._NgayCapNhat != value))
			{
				this.OnNgayCapNhatChanging(value);
				this.SendPropertyChanging();
				this._NgayCapNhat = value;
				this.SendPropertyChanged("NgayCapNhat");
				this.OnNgayCapNhatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="VarChar(10)")]
	public string Size
	{
		get
		{
			return this._Size;
		}
		set
		{
			if ((this._Size != value))
			{
				this.OnSizeChanging(value);
				this.SendPropertyChanging();
				this._Size = value;
				this.SendPropertyChanged("Size");
				this.OnSizeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Int")]
	public System.Nullable<int> Gia
	{
		get
		{
			return this._Gia;
		}
		set
		{
			if ((this._Gia != value))
			{
				this.OnGiaChanging(value);
				this.SendPropertyChanging();
				this._Gia = value;
				this.SendPropertyChanged("Gia");
				this.OnGiaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrlHinh", DbType="NVarChar(500)")]
	public string UrlHinh
	{
		get
		{
			return this._UrlHinh;
		}
		set
		{
			if ((this._UrlHinh != value))
			{
				this.OnUrlHinhChanging(value);
				this.SendPropertyChanging();
				this._UrlHinh = value;
				this.SendPropertyChanged("UrlHinh");
				this.OnUrlHinhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongTonKho", DbType="Int")]
	public System.Nullable<int> SoLuongTonKho
	{
		get
		{
			return this._SoLuongTonKho;
		}
		set
		{
			if ((this._SoLuongTonKho != value))
			{
				this.OnSoLuongTonKhoChanging(value);
				this.SendPropertyChanging();
				this._SoLuongTonKho = value;
				this.SendPropertyChanged("SoLuongTonKho");
				this.OnSoLuongTonKhoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string GhiChu
	{
		get
		{
			return this._GhiChu;
		}
		set
		{
			if ((this._GhiChu != value))
			{
				this.OnGhiChuChanging(value);
				this.SendPropertyChanging();
				this._GhiChu = value;
				this.SendPropertyChanged("GhiChu");
				this.OnGhiChuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnHien", DbType="Int")]
	public System.Nullable<int> AnHien
	{
		get
		{
			return this._AnHien;
		}
		set
		{
			if ((this._AnHien != value))
			{
				this.OnAnHienChanging(value);
				this.SendPropertyChanging();
				this._AnHien = value;
				this.SendPropertyChanged("AnHien");
				this.OnAnHienChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_SanPham_Hinh", Storage="_SanPham_Hinhs", ThisKey="idSP", OtherKey="idSP")]
	public EntitySet<SanPham_Hinh> SanPham_Hinhs
	{
		get
		{
			return this._SanPham_Hinhs;
		}
		set
		{
			this._SanPham_Hinhs.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_ChiTietDonHang", Storage="_ChiTietDonHangs", ThisKey="idSP", OtherKey="idSP")]
	public EntitySet<ChiTietDonHang> ChiTietDonHangs
	{
		get
		{
			return this._ChiTietDonHangs;
		}
		set
		{
			this._ChiTietDonHangs.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiSP_SanPham", Storage="_LoaiSP", ThisKey="idLoai", OtherKey="idLoai", IsForeignKey=true)]
	public LoaiSP LoaiSP
	{
		get
		{
			return this._LoaiSP.Entity;
		}
		set
		{
			LoaiSP previousValue = this._LoaiSP.Entity;
			if (((previousValue != value) 
						|| (this._LoaiSP.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._LoaiSP.Entity = null;
					previousValue.SanPhams.Remove(this);
				}
				this._LoaiSP.Entity = value;
				if ((value != null))
				{
					value.SanPhams.Add(this);
					this._idLoai = value.idLoai;
				}
				else
				{
					this._idLoai = default(Nullable<int>);
				}
				this.SendPropertyChanged("LoaiSP");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChungLoai_SanPham", Storage="_ChungLoai", ThisKey="idCL", OtherKey="idCL", IsForeignKey=true)]
	public ChungLoai ChungLoai
	{
		get
		{
			return this._ChungLoai.Entity;
		}
		set
		{
			ChungLoai previousValue = this._ChungLoai.Entity;
			if (((previousValue != value) 
						|| (this._ChungLoai.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._ChungLoai.Entity = null;
					previousValue.SanPhams.Remove(this);
				}
				this._ChungLoai.Entity = value;
				if ((value != null))
				{
					value.SanPhams.Add(this);
					this._idCL = value.idCL;
				}
				else
				{
					this._idCL = default(Nullable<int>);
				}
				this.SendPropertyChanged("ChungLoai");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_SanPham_Hinhs(SanPham_Hinh entity)
	{
		this.SendPropertyChanging();
		entity.SanPham = this;
	}
	
	private void detach_SanPham_Hinhs(SanPham_Hinh entity)
	{
		this.SendPropertyChanging();
		entity.SanPham = null;
	}
	
	private void attach_ChiTietDonHangs(ChiTietDonHang entity)
	{
		this.SendPropertyChanging();
		entity.SanPham = this;
	}
	
	private void detach_ChiTietDonHangs(ChiTietDonHang entity)
	{
		this.SendPropertyChanging();
		entity.SanPham = null;
	}
}
#pragma warning restore 1591
