<?xml version="1.0" encoding="utf-8"?><Database Name="WebThoiTrang" Class="WebThoiTrangDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=PHUONGIT-PC\SQLEXPRESS;Initial Catalog=WebThoiTrang;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="WebThoiTrangConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SanPham_Hinh" Member="SanPham_Hinhs">
    <Type Name="SanPham_Hinh">
      <Column Name="idHinh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idSP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UrlHinh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Stt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AnHien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SanPham_SanPham_Hinh" Member="SanPham" ThisKey="idSP" OtherKey="idSP" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TroGiupKH" Member="TroGiupKHs">
    <Type Name="TroGiupKH">
      <Column Name="idLL" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LoiKhuyen" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TGLamViec" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ChiNhanhCoHang" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.DonHang" Member="DonHangs">
    <Type Name="DonHang">
      <Column Name="idDHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ThoiDiemDatHang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TenNguoiNhan" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="SoDT" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DiaChiGiaoHang" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="DonHang_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="idDHang" OtherKey="idDHang" Type="ChiTietDonHang" />
    </Type>
  </Table>
  <Table Name="dbo.ChungLoai" Member="ChungLoais">
    <Type Name="ChungLoai">
      <Column Name="idCL" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenCL" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AnHien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ChungLoai_LoaiSP" Member="LoaiSPs" ThisKey="idCL" OtherKey="idCL" Type="LoaiSP" />
      <Association Name="ChungLoai_SanPham" Member="SanPhams" ThisKey="idCL" OtherKey="idCL" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiSP" Member="LoaiSPs">
    <Type Name="LoaiSP">
      <Column Name="idLoai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idCL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AnHien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LoaiSP_SanPham" Member="SanPhams" ThisKey="idLoai" OtherKey="idLoai" Type="SanPham" />
      <Association Name="ChungLoai_LoaiSP" Member="ChungLoai" ThisKey="idCL" OtherKey="idCL" Type="ChungLoai" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuyenTruyCap" Member="QuyenTruyCaps">
    <Type Name="QuyenTruyCap">
      <Column Name="idQuyen" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenQuyen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="QuyenTruyCap_NguoiDung" Member="NguoiDungs" ThisKey="idQuyen" OtherKey="idQuyen" Type="NguoiDung" />
    </Type>
  </Table>
  <Table Name="dbo.NguoiDung" Member="NguoiDungs">
    <Type Name="NguoiDung">
      <Column Name="idUser" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NgayDangKy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idQuyen" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="QuyenTruyCap_NguoiDung" Member="QuyenTruyCap" ThisKey="idQuyen" OtherKey="idQuyen" Type="QuyenTruyCap" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LienHe" Member="LienHes">
    <Type Name="LienHe">
      <Column Name="idLienLac" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ChuDe" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietDonHang" Member="ChiTietDonHangs">
    <Type Name="ChiTietDonHang">
      <Column Name="idDHang" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idSP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Size" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="DonHang_ChiTietDonHang" Member="DonHang" ThisKey="idDHang" OtherKey="idDHang" Type="DonHang" IsForeignKey="true" />
      <Association Name="SanPham_ChiTietDonHang" Member="SanPham" ThisKey="idSP" OtherKey="idSP" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="idSP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idLoai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idCL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Size" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Gia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UrlHinh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SoLuongTonKho" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AnHien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SanPham_SanPham_Hinh" Member="SanPham_Hinhs" ThisKey="idSP" OtherKey="idSP" Type="SanPham_Hinh" />
      <Association Name="SanPham_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="idSP" OtherKey="idSP" Type="ChiTietDonHang" />
      <Association Name="LoaiSP_SanPham" Member="LoaiSP" ThisKey="idLoai" OtherKey="idLoai" Type="LoaiSP" IsForeignKey="true" />
      <Association Name="ChungLoai_SanPham" Member="ChungLoai" ThisKey="idCL" OtherKey="idCL" Type="ChungLoai" IsForeignKey="true" />
    </Type>
  </Table>
</Database>